#!/usr/bin/env python3
"""Assemble a single Luau file that runs the game headlessly.

The game scripts are pasted into functions inside one chunk, with the mock
engine installed as globals first, so `luau tests/run.luau` actually
executes the real server and client code and fails on runtime errors.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def read(rel: str) -> str:
    return (ROOT / rel).read_text()


def main() -> int:
    mock = read("tests/mock.luau")
    config = read("src/shared/Config.luau")
    world = read("src/server/World.server.luau")
    server = read("src/server/Main.server.luau")
    client = read("src/client/Main.client.luau")
    scenario = read("tests/scenario.luau")

    out = f"""-- GENERATED by tests/build_test.py -- do not edit by hand.

local mock = (function()
{mock}
end)()

-- Install the fake engine as globals so the game scripts see it.
local globals = mock.globals()
game = globals.game
workspace = globals.workspace
Instance = globals.Instance
Enum = globals.Enum
Vector3 = globals.Vector3
Vector2 = globals.Vector2
CFrame = globals.CFrame
Color3 = globals.Color3
UDim = globals.UDim
UDim2 = globals.UDim2
NumberRange = globals.NumberRange
NumberSequence = globals.NumberSequence
ColorSequence = globals.ColorSequence
Random = globals.Random
task = globals.task
CatalogSearchParams = globals.CatalogSearchParams
RaycastParams = globals.RaycastParams
typeof = globals.typeof
TweenInfo = globals.TweenInfo

local Config = (function()
{config}
end)()

-- Publish Config the way the game scripts reach it.
local replicatedStorage = game:GetService("ReplicatedStorage")
local sharedFolder = Instance.new("Folder")
sharedFolder.Name = "Shared"
sharedFolder.Parent = replicatedStorage
local configModule = Instance.new("ModuleScript")
configModule.Name = "Config"
configModule.Parent = sharedFolder

local moduleResults = {{ [configModule] = Config }}
require = function(target)
	local result = moduleResults[target]
	if result == nil then
		error("require() of an unregistered module", 0)
	end
	return result
end

local function runWorldScript()
{world}
end

local function runServerScript()
{server}
end

local function runClientScript()
{client}
end

local scenario = {{
	mock = mock,
	Config = Config,
	runWorldScript = runWorldScript,
	runServerScript = runServerScript,
	runClientScript = runClientScript,
}}

{scenario}
"""

    target = ROOT / "tests" / "run.luau"
    target.write_text(out)
    print(f"wrote {target} ({len(out.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
